In [1]:
#task1
import numpy as np
print(np.__version__)

2.3.3


In [2]:
print(np.arange(10, 100,3))

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [6]:
#task2

arr = np.linspace(0,1,100)
print(arr)
print("T02 - Linear Spacing & Endpoints")
print(f"first: {arr[0]}, last: {arr[-1]}, count: {arr.size}")
print(f"step size: {arr[1] - arr[0]:.6f}\n")

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [ ]:
#task3
print(np.eye(5))
print(np.full((3,4),7))
print(np.empty((2,3)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.78145267e-307 2.67019999e-306 1.05699581e-307]]


In [14]:
#task4
arr = np.array([1.7, 2.3, 3.9])
print(arr)
as_int = arr.astype(np.int32)
as_boot = arr.astype(bool)
print(as_int)
print(as_boot)

[1.7 2.3 3.9]
[1 2 3]
[ True  True  True]


In [16]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float64)
print(arr)

print("T05 - Array Metadata & Memory Layout")
print(f"ndim (dimensions):   {arr.ndim}")
print(f"shape:               {arr.shape}")
print(f"size (total elems):  {arr.size}")
print(f"dtype:               {arr.dtype}")
print(f"itemsize (bytes):    {arr.itemsize}")
print(f"nbytes (total bytes):{arr.nbytes}\n")

[[1. 2. 3.]
 [4. 5. 6.]]
T05 - Array Metadata & Memory Layout
ndim (dimensions):   2
shape:               (2, 3)
size (total elems):  6
dtype:               float64
itemsize (bytes):    8
nbytes (total bytes):48



In [17]:
#task6

log_arr = np.logspace(1,5,50)
print("T06 - Logarithmic Grid Generation")
print(f"first: {log_arr[0]}, last: {log_arr[-1]}, count: {log_arr.size}\n")

T06 - Logarithmic Grid Generation
first: 10.0, last: 100000.0, count: 50



In [18]:
#task7 2D grid

x = np.linspace(-2,2,50)
y = np.linspace(-2,2,50)

grid = np.meshgrid(x,y)
print(grid)

(array([[-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       ...,
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ]], shape=(50, 50)), array([[-2.        , -2.        , -2.        , ..., -2.        ,
        -2.        , -2.        ],
       [-1.91836735, -1.91836735, -1.91836735, ..., -1.91836735,
        -1.91836735, -1.91836735],
       [-1.83673469, -1.83673469, -1.83673469, ..., -1.83673469,
        -1.83673469, -1.83673469],
       ...,
       [ 1.83673469,  1.83673469,  1.83673469, ...,  1.83

In [20]:
#task8

matrix = np.arange(36).reshape(6, 6)
print(matrix)
#now extracting submatrix
sub_matrix = matrix[2:5, 3:6]
print(sub_matrix)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[15 16 17]
 [21 22 23]
 [27 28 29]]


In [23]:
#task9

reversal_strides = np.arange(24).reshape(4,6)
reversal_strides

reversed_rows = reversal_strides[::-1, :]
reversed_rows

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [ ]:
border_extraction = np.arange(25).reshape(5,5)
border = np.concatenate((border_extraction[0,:]), border_extraction[-1,:])