In [2]:
#task1
import numpy as np
print(np.__version__)

1.26.4


In [3]:
print(np.arange(10, 100,3))

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [4]:
#task2

arr = np.linspace(0,1,100)
print(arr)
print("T02 - Linear Spacing & Endpoints")
print(f"first: {arr[0]}, last: {arr[-1]}, count: {arr.size}")
print(f"step size: {arr[1] - arr[0]:.6f}\n")

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [5]:
#task3
print(np.eye(5))
print(np.full((3,4),7))
print(np.empty((2,3)))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[1.48539705e-313 1.48539705e-313 1.48539705e-313]
 [1.48539705e-313 1.48539705e-313 1.48539705e-313]]


In [6]:
#task4
arr = np.array([1.7, 2.3, 3.9])
print(arr)
as_int = arr.astype(np.int32)
as_boot = arr.astype(bool)
print(as_int)
print(as_boot)

[1.7 2.3 3.9]
[1 2 3]
[ True  True  True]


In [7]:
arr = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.float64)
print(arr)

print("T05 - Array Metadata & Memory Layout")
print(f"ndim (dimensions):   {arr.ndim}")
print(f"shape:               {arr.shape}")
print(f"size (total elems):  {arr.size}")
print(f"dtype:               {arr.dtype}")
print(f"itemsize (bytes):    {arr.itemsize}")
print(f"nbytes (total bytes):{arr.nbytes}\n")

[[1. 2. 3.]
 [4. 5. 6.]]
T05 - Array Metadata & Memory Layout
ndim (dimensions):   2
shape:               (2, 3)
size (total elems):  6
dtype:               float64
itemsize (bytes):    8
nbytes (total bytes):48



In [8]:
#task6

log_arr = np.logspace(1,5,50)
print("T06 - Logarithmic Grid Generation")
print(f"first: {log_arr[0]}, last: {log_arr[-1]}, count: {log_arr.size}\n")

T06 - Logarithmic Grid Generation
first: 10.0, last: 100000.0, count: 50



In [9]:
#task7 2D grid

x = np.linspace(-2,2,50)
y = np.linspace(-2,2,50)

grid = np.meshgrid(x,y)
print(grid)

[array([[-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       ...,
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ],
       [-2.        , -1.91836735, -1.83673469, ...,  1.83673469,
         1.91836735,  2.        ]]), array([[-2.        , -2.        , -2.        , ..., -2.        ,
        -2.        , -2.        ],
       [-1.91836735, -1.91836735, -1.91836735, ..., -1.91836735,
        -1.91836735, -1.91836735],
       [-1.83673469, -1.83673469, -1.83673469, ..., -1.83673469,
        -1.83673469, -1.83673469],
       ...,
       [ 1.83673469,  1.83673469,  1.83673469, ...,  1.83673469,
        

In [10]:
#task8

matrix = np.arange(36).reshape(6, 6)
print(matrix)
#now extracting submatrix
sub_matrix = matrix[2:5, 3:6]
print(sub_matrix)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[15 16 17]
 [21 22 23]
 [27 28 29]]


In [11]:
#task9

reversal_strides = np.arange(24).reshape(4,6)
reversal_strides

reversed_rows = reversal_strides[::-1, :]
reversed_rows

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [12]:
border_extraction = np.arange(25).reshape(5,5)
border = np.concatenate([(border_extraction[0,:]), border_extraction[-1,:]])

In [13]:
# start here the actual numpy code pratcies task
#TASK 1

student_ids = np.array(["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10"])
hours = np.array([1,1,1,2,3,4,4,4,4,5])
attendance = np.array([62,45,67,58,62,69,75,81,63,75])
previous = np.array([62,75,64,44,62,52,53,56,60,45])
final_marks = np.array([41,46,56,44,57,58,58,67,67,53])
pass_status = np.array([0,0,0,0,0,0,0,1,1,0])
assignment = np.array([42,64,43,56,52,48,56,52,73,60])

In [14]:
'''
1. Create a 1-D array from the list [10, 20, 30, 40, 50].
2. Create arrays using np.zeros(), np.ones(), np.full(), np.arange(), and np.linspace().
3. Create a 3x4 zero matrix and then a 4x4 identity matrix.
4. Print each array and its dtype.
'''
#1
oned_array = np.array([10,20,30,40,50])
print("1-D Array:", oned_array)
#2
zeros_array = np.zeros(5)
print("Zeros Array:", zeros_array, "Data Type:", zeros_array.dtype)

ones_array = np.ones((4,8))
ones_array

full_array = np.full((4,4), 9) # 2d with 4 r & 4 c with val of 9
full_array

arange_array = np.arange(0,20,4) #with jump of 4
arange_array

linspace_array = np.linspace(1, 10, 20)
linspace_array

#3
zeros_matrix = np.zeros((3,4))
zeros_matrix

identity_matrix = np.eye(4)
identity_matrix

#4
print('1D array:', oned_array, 'data type:', oned_array.dtype)
print('zeros array:', zeros_array, 'data type:', zeros_array.dtype)
print('ones array:', ones_array, 'data type:', ones_array.dtype)
print('full array:', full_array, 'data type:', full_array.dtype)
print('arange array:', arange_array, 'data type:', arange_array.dtype)
print('linspace array:', linspace_array, 'data type:', linspace_array.dtype)
print('zeros matrix:', zeros_matrix, 'data type:', zeros_matrix.dtype)
print('identity matrix:', identity_matrix, 'data type:', identity_matrix.dtype)

1-D Array: [10 20 30 40 50]
Zeros Array: [0. 0. 0. 0. 0.] Data Type: float64
1D array: [10 20 30 40 50] data type: int32
zeros array: [0. 0. 0. 0. 0.] data type: float64
ones array: [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]] data type: float64
full array: [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]] data type: int32
arange array: [ 0  4  8 12 16] data type: int32
linspace array: [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ] data type: float64
zeros matrix: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] data type: float64
identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] data type: float64


arange is more convient than linspace. both have different purpose rather has some outputs are same. arange work same like range builtin function of python yet memory optimzed. linspace return the inbetween elements of the specified range now matter how small we specify to cut or divide.

In [15]:
#TASK2
'''
5. For hours, attendance and a 2-D matrix of your choice, print ndim, shape, size, dtype and itemsize.
6. Convert hours to float64 and assignment to int16 using astype().
7. Check the dtype before and after conversion.
8. Create an array mixing integers and decimals. Observe NumPy type promotion.
'''
#5
print('for attendance array:', attendance.ndim, attendance.shape, attendance.size, attendance.dtype,
attendance.itemsize)
print('for attendance array:', hours.ndim, hours.shape, hours.size, hours.dtype,
hours.itemsize)

#6
hours_float = hours.astype(np.float64)
print('hours array before conversion:', hours.dtype, 'after conversion:', hours_float.dtype)
assignment_int = assignment.astype(np.int16)
print('before conversion:', assignment.dtype, 'after conversion:', assignment_int.dtype)
#7
promotion_array = np.array([1, 5.4, 2.9, 4.5, 2.1, 15,9])
print('promotion array:', promotion_array, 'data type:', promotion_array.dtype)

for attendance array: 1 (10,) 10 int32 4
for attendance array: 1 (10,) 10 int32 4
hours array before conversion: int32 after conversion: float64
before conversion: int32 after conversion: int16
promotion array: [ 1.   5.4  2.9  4.5  2.1 15.   9. ] data type: float64


In [16]:
'''
Task 3 — 2-D and 3-D Arrays
9. Create a 3x4 array containing numbers 1 to 12.
10. Create a 2x3x4 array containing numbers 1 to 24.
11. Print shape and ndim for both arrays.
12. Access one element from each dimension level of the 3-D array.
'''
three_by_four_array = np.arange(1, 13).reshape(3,4)
print('3*4 array:', three_by_four_array)

two_by_three_by_four_array = np.arange(1,25).reshape(2,3,4)
print('2*3*4 array:', two_by_three_by_four_array)
print('shape and ndim of 3*4 array:', three_by_four_array.shape, three_by_four_array.ndim)
print('shape and ndim of 2*3*4 array:', two_by_three_by_four_array.shape, two_by_three_by_four_array.ndim)

print('accessing one element from each dimension lvel of 3-D array:', two_by_three_by_four_array[1,2,3])


3*4 array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2*3*4 array: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape and ndim of 3*4 array: (3, 4) 2
shape and ndim of 2*3*4 array: (2, 3, 4) 3
accessing one element from each dimension lvel of 3-D array: 24


In [17]:
'''
Task 4 — Indexing Practice
13. Print the first, last and fifth values of final_marks.
14. Use negative indexing to access the last three values one by one.
15. From a 3x4 matrix, access row 2 column 3.
16. Use an array of indexes to select students at positions 0, 3, 7 and 9.
'''

print('first last and fifth values of final_marks:',final_marks[0], final_marks[-1], final_marks[5])
print('last three valuse one by one:', final_marks[-1], final_marks[-2], final_marks[-3])

print('accessing  row 2 and col 3:', three_by_four_array[1,2])

indexes = np.array([0, 3, 7, 9])
print('selected students:', final_marks[indexes]) # this we can get by double square brackets as well but this is more efficient and better way to do it internally it is like final_marks [[indexes]]

first last and fifth values of final_marks: 41 53 58
last three valuse one by one: 53 67 67
accessing  row 2 and col 3: 7
selected students: [41 44 67 53]


In [18]:
'''
Task 5 — Slicing Practice
17. From attendance, extract the first five values.
18. Extract values from index 2 up to index 7.
19. Extract every second value.
20. Reverse the array using slicing.
21. From a 2-D matrix, slice the first two rows and columns 1 to 3.
'''

print('from attendance first five val', attendance[0:5])
print('from 2 up to 7:', attendance[2:8])
print('extract every 2nd value:', attendance[::2])
print('reverse of array',attendance[::-1])
print(three_by_four_array[0:2, 1:4]) # first two rows and columns 1 to 3

from attendance first five val [62 45 67 58 62]
from 2 up to 7: [67 58 62 69 75 81]
extract every 2nd value: [62 67 62 75 63]
reverse of array [75 63 81 75 69 62 58 67 45 62]
[[2 3 4]
 [6 7 8]]


In [19]:
'''
22. Find all students whose final marks are 60 or above.
23. Find attendance values below 70.
24. Find students who studied at least 4 hours AND attended at least 70%.
25. Find students with marks between 50 and 70 inclusive.
26. Use the boolean mask to print matching student IDs.
Challenge: Create one condition using OR and one using NOT.
'''

print('student with 60 or above final marks:', student_ids[final_marks >= 60])
print('attendanace below 70:', attendance[attendance < 70])
print(student_ids[(hours>=4) & (attendance >= 70)])
print(student_ids[(final_marks >= 50) & (final_marks <= 70)])
# challenge
print(student_ids[(attendance != 70) | (attendance <= 70)])

student with 60 or above final marks: ['S08' 'S09']
attendanace below 70: [62 45 67 58 62 69 63]
['S07' 'S08' 'S10']
['S03' 'S05' 'S06' 'S07' 'S08' 'S09' 'S10']
['S01' 'S02' 'S03' 'S04' 'S05' 'S06' 'S07' 'S08' 'S09' 'S10']


In [20]:
'''Task 7 — Copy vs View
27. Create a slice of hours and modify it. Observe whether the original changes.
28. Create a copy using .copy(), modify the copy, and compare it with the original.
29. Use np.shares_memory() to test whether two arrays share memory.
30. Write one sentence describing the practical difference between a view and a copy.'''

sliced_hours = hours[:5]
sliced_hours[0] = 25
print(hours)
sliced_hours # original changed

copied_hours = hours.copy()

copied_hours[0] = 35

print(copied_hours)
print(hours)

np.shares_memory(hours, sliced_hours) # false with hours and copied hours | true with hours and sliced hours

#view modified the orignal and copy method make a seperate copy of that object



[25  1  1  2  3  4  4  4  4  5]
[35  1  1  2  3  4  4  4  4  5]
[25  1  1  2  3  4  4  4  4  5]


True

In [21]:
'''
31. Reshape np.arange(1, 13) into 3x4 and then 4x3.
32. Reshape it into 2x2x3.
33. Flatten a 2-D array using flatten() and ravel().
34. Transpose a 3x4 matrix.
35. Compare the shapes before and after transpose.
Challenge: Try reshape(-1, 2) and explain what -1 tells NumPy to do.
'''


array_to_be_reshaped = np.arange(1,13).reshape(3,4)

print(array_to_be_reshaped)

print(array_to_be_reshaped.reshape(4,3))

print(array_to_be_reshaped.reshape(2,2,3))

print('transpose array:', array_to_be_reshaped.transpose())

#flatterning 2d array

array_to_be_reshaped.flatten()


print(array_to_be_reshaped.ravel())
print('original:', array_to_be_reshaped)

# I have checked both flatten and ravel method they don't modify the orignal one they just return new copy of 1d array.

# after transpose it change the shape 3 4 to 4 3. basically transpose method conert row into cols and cols into rows.
print(array_to_be_reshaped.reshape(-1,2)) # it make 2 d array of of 2 cols 6 rows



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
transpose array: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
original: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [22]:
'''
36. Loop over a 1-D array normally.
37. Loop over every element of a 2-D array using nested loops.
38. Use np.nditer() on the same 2-D array.
39. Use np.ndenumerate() and print index-value pairs for the first few elements.
'''

#loop over 1d array i am using hours array
for i in hours:
    print(i,end=',')

print()
#loop over every element of a 2d array using nested loops
two_d_array = np.arange(1,13).reshape(3,4)

for rows in two_d_array:
    print(rows)
    for el in rows:
        print(el)

print("using nditer")
# using nditer
for rows in np.nditer(two_d_array):
    print(rows, end=" ")
    # for el in np.nditer(rows):
    #     print(el,end=" ")
# i run first i nesting it work same but when comment out nested an print row get the same result mean no matter the dimneisno or shape it iter over every element
print()

# using ndenumerate printing first few welemtn of array hours

for key, value in np.ndenumerate(hours):
    print(f'key: {key[0]}    value:{value}')


25,1,1,2,3,4,4,4,4,5,
[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
[ 9 10 11 12]
9
10
11
12
using nditer
1 2 3 4 5 6 7 8 9 10 11 12 
key: 0    value:25
key: 1    value:1
key: 2    value:1
key: 3    value:2
key: 4    value:3
key: 5    value:4
key: 6    value:4
key: 7    value:4
key: 8    value:4
key: 9    value:5


In [23]:
'''
40. Concatenate hours and attendance into one long 1-D array.
41. Create a two-column matrix using np.column_stack((hours, final_marks)).
42. Try vstack() and hstack() with compatible arrays.
43. Split a 12-element array into 3 equal parts.
44. Use array_split() on an array whose length cannot be divided equally.
'''
#1
#first i am doing passing directly the arguement like .concatenate(hours , attendance) facing error not to add scaler integers type than i realized that they are vectors consider in numpy or to concat in this way, aslo i passed tuple i.e with () and with [] getting the same output confse in the difference

np.concatenate([hours, attendance]) # actaully a this is core function to join horizonatally or vercially by passing axis arg

# they pure to stack specify with names

#2
np.column_stack((hours, final_marks)) # i observe in the output it make 2 columns of thier entires i.e booth are 1d arrays.

#3
np.vstack((hours, final_marks)) # it make these 1 d arrays into 2d like hours above and marks below like vertical stacking as clear in function name it stack row wise

np.hstack((hours,assignment, student_ids)) # i see in output result it convert both array like smae way it concat the 2 arrays and so on. what is the differnece between concat and hstack. like assuming it stack column wise

#4
array_to_be_splitted = np.arange(0,12)
np.split(array_to_be_splitted, 3) # i tried on mulitple val like 4 it wokr when pass 5 it can splitte i think it divid it length and if whole ans then return the spplitted verison other wise raise value error

#5 array split
cannot_dividable_array = np.arange(1, 17)

np.array_split(cannot_dividable_array, 5) # ah this is majic it does through error it divid such that first of four entres and rest of 3 entries.




[array([1, 2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 13]),
 array([14, 15, 16])]

In [24]:
'''
45. Use np.where() to find positions where final_marks >= 60.
46. Use np.argmax() and np.argmin() to locate the highest and lowest final marks.
47. Find unique values and counts in hours using np.unique(..., return_counts=True).
48. Sort attendance in ascending order.
49. Use argsort() to sort student_ids according to final_marks.
Challenge: Print the top 3 students by final marks without manually typing their indexes.
'''
#1
np.where([final_marks>=60])
#2
np.argmax(final_marks); np.argmin(final_marks);

#3
np.unique(hours, return_counts=True) # return tuple of unique array and their count in 2nd array

#4
np.sort(attendance)

#5
final_marks_index = np.argsort(final_marks)
print(student_ids[final_marks_index])

#challenge
top3student = np.argsort([student_ids, final_marks])

top3student
for i in range(3):
     print(f'student_ids: {student_ids[top3student[0,-1-i]]} with marks: {final_marks[top3student[1,-1-i]]}')
     # print(f'student_ids: {student_ids[top3student[0,-2]]} with marks: {final_marks[top3student[1,-2]]}')
     # print(f'student_ids: {student_ids[top3student[0,-3]]} with marks: {final_marks[top3student[1,-3]]}')


print(f'student_ids: {student_ids[top3student[0,-1:-4]]} with marks: {final_marks[top3student[1,-1:-4]]}')
# i have checked by both now i understand in negative silitcing moveing toward left we hsoul explcity pass negative step size by default it move forward when pass negative it mover twoars left

top3student[0,-1: -4: -1]

['S01' 'S04' 'S02' 'S10' 'S03' 'S05' 'S06' 'S07' 'S08' 'S09']
student_ids: S10 with marks: 67
student_ids: S09 with marks: 67
student_ids: S08 with marks: 58
student_ids: [] with marks: []


array([9, 8, 7], dtype=int64)

In [25]:
'''
Task 12 — Filtering and np.where Transformation
50. Create a filtered array of assignment scores above 55.
51. Use np.where() to replace marks below 50 with 50 in a new array.
52. Create labels High/Medium/Low based on final marks using np.select() or nested np.where().
53. Count how many values fall into each label.
'''
#1
assignment[assignment > 55]

#2
filtered_marks = np.where(final_marks < 50) # npwhere method return tuple of 2 arr first o,o,o and then the actual indexes so ipasssed 1 as arg
new_marks = final_marks.copy()
print(new_marks)
print(filtered_marks)
new_marks[filtered_marks[0]] = 50

#3
cat_marks =np.select(
    [final_marks<50,
     (final_marks>=50) & (final_marks <=60),
     final_marks>60
    ],
    ['low', 'medium', 'high'],
    default = 'low'
)
print(cat_marks)
countlow= 0 
countmedium =0 
counthigh = 0
for i in cat_marks:
    if i == 'low':
        countlow+=1
    elif i== 'medium':
        countmedium+=1
    else:
        counthigh+=1

print(f'low:{countlow} medium:{countmedium} high:{counthigh}')


# other is unique method
value, count = np.unique(final_marks, return_counts=True) 

# valuecat, countcat = np.unique(cat_marks, return_counts=True) 
dict(zip(value, count))

[41 46 56 44 57 58 58 67 67 53]
(array([0, 1, 3], dtype=int64),)
['low' 'low' 'medium' 'low' 'medium' 'medium' 'medium' 'high' 'high'
 'medium']
low:3 medium:5 high:2


{41: 1, 44: 1, 46: 1, 53: 1, 56: 1, 57: 1, 58: 2, 67: 2}

In [26]:
'''
54. Compute sum, mean, median, min, max, standard deviation and variance of final_marks.
55. Compute percentile 25, 50 and 75.
56. Calculate the range of attendance.
57. Round a decimal array to 2 decimal places.
58. Use np.sqrt(), np.abs(), np.power() and np.clip() on small example arrays.
'''

final_marks.sum()
final_marks.mean()
final_marks.min()
final_marks.max()
final_marks.std()
final_marks.var()
print(np.median(final_marks)) #median
np.percentile(final_marks, 25)
np.percentile(final_marks, 50)
np.percentile(final_marks, 75)
array_to_be_rounded = np.array([2.5543,2.542,9.25252,0.2585])
np.round(array_to_be_rounded, 2)

np.sqrt(final_marks)
np.abs(hours)
np.power(hours, 2)
np.clip(final_marks, 50,60) # replace the value with 50 if it below 50 and replce value with 60 if it greater than 60

np.ptp(attendance) # range formula is max - min


# we can do this way as well
np.max(attendance) - np.min(attendance)
attendance.max() - attendance.min()

56.5


36

In [27]:
'''
59. Create a 4x3 matrix where columns represent Hours, Attendance and Final Marks for four students.
60. Find the mean of each column using axis=0.
61. Find the mean of each student row using axis=1.
62. Add [1, 2, 3] to every row using broadcasting.
63. Standardize each column manually: (x - column_mean) / column_std.
Challenge: Explain why you did not need a Python loop for the broadcasting operation.
'''
# four_students_data = np.array([student_ids[:4], hours[:4], attendance[:4], final_marks[:4]]).transpose()
four_students_data = np.array([hours[:4], attendance[:4], final_marks[:4]]).transpose()
# four_students_data[:,0].mean() # test
four_students_data.mean(axis=0)
four_students_data.mean(axis=1)

four_students_data + [1,2,3]
# np.concatenate([four_students_data, [[1,2,3]]]) just to check it append in the last fir i got errro of passing 1d array saying thta dimenison has same so i doubled the sq brcker

#standardization
(final_marks - final_marks.mean())/final_marks.std()

# i did'nt use loop for broadcasting if i use it is a tradtional  way to addd it here is the code of it
to_add = np.array([1,2,3])
for row in range(len(four_students_data)):
    four_students_data[row] += to_add

four_students_data

data_mean = four_students_data.mean(axis=0)
data_std = four_students_data.std(axis=0)
#hours mean
for i in range(3):
    print(f' normalized data : {four_students_data[:,i] - data_mean[i]/data_std[i]}')


 normalized data : [25.19560033  1.19560033  1.19560033  2.19560033]
 normalized data : [56.64232793 39.64232793 61.64232793 52.64232793]
 normalized data : [35.16209973 40.16209973 50.16209973 38.16209973]


In [28]:
'''
Task 15 — Random Module and Reproducibility
64. Use np.random.default_rng(42) to create a random-number generator.
65. Generate 10 random integers between 40 and 100.
66. Generate 5 random floats between 0 and 1.
67. Randomly select 3 student IDs without replacement.
68. Shuffle an array.
69. Generate a small normal-distribution sample with mean 70 and standard deviation 10.
'''

random_num = np.random.default_rng(42)
random_num.integers(10)

#2
random_num.integers(40,100, size=10)

#3 random array of float b/w 0 & 1

random_num.random(size=5)

random_num.choice(student_ids, 3)

random_num.shuffle(student_ids)
student_ids # modifed the orignal

random_num.normal(70, 10, size=(10)) # pick random and distribute normally.

# I run the same seed twice and it print the same value again and again

array([60.41117399, 78.78450301, 69.50074089, 68.15137636, 63.19070456,
       82.22541339, 68.45470518, 65.71672178, 66.4786645 , 75.32309186])

In [29]:
'''
Task 16 — Missing Values and Vectorized Cleaning
70. Create marks_with_nan = np.array([60, 72, np.nan, 55, 90, np.nan, 68]).
71. Detect missing values with np.isnan().
72. Count the missing values.
73. Calculate the mean while ignoring NaN using np.nanmean().
74. Replace NaN values with the non-missing mean using vectorized indexing.
75. Clip cleaned marks into the range 0 to 100.
Challenge: Do the replacement without writing an explicit Python for-loop
'''

marks_with_nan = np.array([60, 72,np.nan, 55, 90, np.nan, 68])

np.isnan(marks_with_nan) # return a boolean array true where value is not a number
val, count = np.unique(marks_with_nan, return_counts= True) # return values and counts
count

#73
np.nanmean(marks_with_nan) # ignore nan in array what if i do with smple mean
# np.mean(marks_with_nan) 
# return nan

#74 we shhoudl use boolean indexing

marks_with_nan[np.isnan(marks_with_nan)] = np.nanmean(marks_with_nan) # now i understnad the crrect us of boolean indexing and also awar of function aobut isnan also itr on it and return boolean arr

marks_with_nan

#75 clip range from 0 to 100
np.clip(marks_with_nan, 0, 100) # clean not to be negative and will not exceed to 100

#challenge  inverse
# for i in np.isnan(marks_with_nan):
#     marks_with_nan[i] = 80

# marks_with_nan

# i testing just dummy of non mean and it working

array([60., 72., 69., 55., 90., 69., 68.])

In [30]:
'''
Task 17 — Build a Student Matrix
76. Create a numeric 2-D matrix with columns: Hours_Studied, Attendance, Assignment_Score,
Previous_Marks, Final_Marks.
77. Print its shape and verify that rows represent students.
78. Compute mean, minimum, maximum and standard deviation for every column using axis=0.
79. Find the student index with the highest Final_Marks and print the matching Student_ID.
80. Find all students whose Final_Marks are above the class mean.
81. Calculate how many students pass using the rule Final_Marks >= 60.
82. Create a boolean array for pass/fail and compare it with pass_status.
'''

# whole_data = np.array([student_ids,hours, attendance, assignment, previous, final_marks]).transpose() #it explictly convert whole arr to string
whole_data = np.array([hours, attendance, assignment, previous, final_marks]).transpose()
print(whole_data)



whole_data.shape # i take transpose and each row containing exactly one reocrd of student now is perfect i think

#78
whole_data.mean(axis=0)
whole_data.min(axis=0)
whole_data.max(axis=0)
whole_data.std(axis=0)

#79

# np.where([whole_data[:, -1].max()])
data = whole_data[:,-1]
max_index = whole_data[:,-1].argmax()

print(f'{student_ids[max_index]} : with its data {whole_data[max_index]}')

#80
mean_marks = final_marks.mean()
mean_marks

np.where(final_marks>= mean_marks)

student_ids[np.where(final_marks>= mean_marks)]
#81
marks_greater_60 = len(data[data>=60])
print(f' student who have marks_greater_60: {marks_greater_60} ')

#82
boolean_array = pass_status.astype(bool)
boolean_array

final_status = pass_status[final_marks>=60]

final_status



[[25 62 42 62 41]
 [ 1 45 64 75 46]
 [ 1 67 43 64 56]
 [ 2 58 56 44 44]
 [ 3 62 52 62 57]
 [ 4 69 48 52 58]
 [ 4 75 56 53 58]
 [ 4 81 52 56 67]
 [ 4 63 73 60 67]
 [ 5 75 60 45 53]]
S10 : with its data [ 4 81 52 56 67]
 student who have marks_greater_60: 2 


array([1, 1])

In [ ]:
'''
Task 18 — Feature Engineering with NumPy
83. Create a new feature called Study_Efficiency = Final_Marks / Hours_Studied. Handle division safely if you
add a zero-hour student.
84. Create Attendance_Band: Low (<60), Medium (60–79), High (>=80).
85. Create a normalized Final_Marks feature using min-max normalization.
86. Create a standardized Attendance feature using z-score standardization.
87. Create a weighted performance score: 20% attendance + 30% assignment + 20% previous marks + 30%
final marks.
88. Rank students from highest to lowest weighted score using argsort().
89. Print the top 3 Student_ID values and their scores.
90. Use np.corrcoef() to calculate correlation between Hours_Studied and Final_Marks.
91. Write 3 short conclusions from your results.
Challenge: Bonus: Add one deliberate outlier (e.g., attendance=150), detect it with a rule, and fix it using
np.clip().
'''

study_efficiency = final_marks / hours
out = np.zeros_like(study_efficiency, dtype=float)
study_efficiency = np.divide(final_marks, hours, out = out , where=(hours!=0))

study_efficiency

#4 attendance band
attendance_band = np.select(
    [
        attendance < 60,
        (attendance >= 60) & (attendance < 80),
        attendance >= 80,
    ],
    ["Low", "Medium", "High"],
    default="low"
)
attendance_band

#5 final marks minmax normalization formula i think is the x - min / max - min

(final_marks - final_marks.min())/(final_marks.max() - final_marks.min())

#6 standardize attendance

(attendance - attendance.mean())/attendance.std()

#challenge
np.clip(attendance, 0, 100) # to handle outlier

#90 correlation between hours and final marks
np.corrcoef(hours, final_marks)

#3 short conculiton from results
'''
by seeing the result in 2d arr final_marks are really good correlate with each other. logical conclusion that i derived is more hours you 
studied you will get better result in the final exams. as correlation is postive and above 0.5 which consider good not tto strong so the 
conclusion is they are correlated with each other
'''

#4 actaully this callucate for each indivictual studnet with their attendance assignment previous final_marks
weighted_score = (
      0.20 * attendance
    + 0.30 * assignment
    + 0.20 * previous
    + 0.30 * final_marks
)

print(weighted_score)
ranking = np.argsort(weighted_score)[::-1]
print(ranking)

# first reverst the ranking than pic top 3 this is the best way actually

top3 = ranking[:3]
print(student_ids[top3])
print(weighted_score[top3])
# print(f'student_ids: {student_ids[top3student[0,-1:-4]]} with marks: {final_marks[top3student[1,-1:-4]]}')

[49.7 57.  55.9 50.4 57.5 56.  59.8 63.1 66.6 57.9]
[8 7 6 9 4 1 5 2 3 0]
['S02' 'S10' 'S06']
[66.6 63.1 59.8]
